"""Regenerate docs/API.md, docs/DATABASE.md and docs/PERMISSIONS.md from the code.

    python scripts/gen_docs.py
"""

import os
import sys
from pathlib import Path

os.environ.setdefault("AUTO_MIGRATE", "false")
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

DOCS = Path(__file__).resolve().parents[2] / "docs"


def permissions() -> str:
    from app.core.rbac import DEFAULT_ROLES, PERMISSIONS

    lines = ["# Permissions & roles", "", "_Generated by `backend/scripts/gen_docs.py` from `app/core/rbac.py`. Do not edit by hand._", "",
             "Every API route enforces its permission on the server (`require(...)` dependency). The web UI hides what a role cannot use, "
             "but hiding is only a convenience — the backend is the authority.", "", "## Permission catalogue", ""]
    for module, group in PERMISSIONS.items():
        lines += [f"### {module}", "", "| Code | Grants |", "|---|---|"]
        lines += [f"| `{code}` | {desc} |" for code, desc in group.items()]
        lines.append("")
    lines += ["## Default roles", ""]
    all_codes = [c for g in PERMISSIONS.values() for c in g]
    for role, spec in DEFAULT_ROLES.items():
        perms = list(dict.fromkeys(spec["permissions"]))
        lines += [f"### {role}", "", spec["description"], "", f"{len(perms)} of {len(all_codes)} permissions.", ""]
        if len(perms) < len(all_codes):
            lines += ["`" + "`, `".join(perms) + "`", ""]
        else:
            lines += ["All permissions.", ""]
    lines += [
        "## Notes", "",
        "- **Cost visibility:** `product.cost` controls whether purchase price, stock value, COGS and profit columns are returned. "
        "Cashiers and inventory managers never receive them.",
        "- **Discount authority:** cashiers may give manual discounts up to the shop limit (default 5%, per-user override possible). "
        "`discount.override` lifts the limit.",
        "- **Credit sales** need `sale.credit`, a registered customer and available credit limit.",
        "- Only a **Super Admin** can assign or modify the Super Admin role; `role.manage` and `backup.manage` are Super-Admin-only by default.",
        "- Custom roles can be created under Settings → Roles & permissions.",
    ]
    return "\n".join(lines) + "\n"


def database() -> str:
    import app.models  # noqa: F401
    from app.core.database import Base

    lines = ["# Database schema", "", "_Generated from the SQLAlchemy models by `backend/scripts/gen_docs.py`._", "",
             f"{len(Base.metadata.tables)} tables. Migrations live in `backend/alembic/versions`. Money is `NUMERIC(14,2)`, quantities `NUMERIC(14,3)`, "
             "all timestamps are stored as UTC.", "",
             "Financial records are never physically deleted: sales are voided, expenses voided, products/suppliers/customers/employees soft-deleted.", ""]
    for name in sorted(Base.metadata.tables):
        t = Base.metadata.tables[name]
        lines += [f"## `{name}`", "", "| Column | Type | Null | Notes |", "|---|---|---|---|"]
        for c in t.columns:
            notes = []
            if c.primary_key:
                notes.append("PK")
            for fk in c.foreign_keys:
                notes.append(f"FK → `{fk.column.table.name}.{fk.column.name}`")
            if c.unique:
                notes.append("unique")
            if c.index:
                notes.append("indexed")
            lines.append(f"| `{c.name}` | {c.type} | {'yes' if c.nullable else 'no'} | {', '.join(notes)} |")
        extras = [f"unique({', '.join(col.name for col in u.columns)})" for u in t.constraints if u.__class__.__name__ == "UniqueConstraint" and len(u.columns) > 1]
        extras += [f"check `{c.sqltext}`" for c in t.constraints if c.__class__.__name__ == "CheckConstraint"]
        if extras:
            lines += ["", "Constraints: " + "; ".join(extras)]
        lines.append("")
    return "\n".join(lines) + "\n"


def api() -> str:
    from app.main import app

    spec = app.openapi()
    lines = ["# REST API", "", "_Generated from the FastAPI OpenAPI schema by `backend/scripts/gen_docs.py`._", "",
             "Interactive docs (Swagger UI) are served at `/docs` and `/redoc` whenever `ENVIRONMENT` is not `production`; the raw schema is `/openapi.json`.", "",
             "## Conventions", "",
             "- Base path `/api/v1`. JSON in, JSON out. Authenticate with `Authorization: Bearer <access token>` (get one from `POST /auth/login`).",
             "- **Lists** return `{items, total, page, page_size, pages}` and accept `page`, `page_size` (max 200), `search`, `sort` (`name` / `-name`) plus route-specific filters.",
             "- **Errors** always look like `{\"error\": {\"code\": \"insufficient_stock\", \"message\": \"...\", \"details\": {...}, \"request_id\": \"...\"}}`. "
             "Common codes: `validation_error` (422), `unauthorized` (401), `forbidden` (403), `not_found` (404), `conflict` / `duplicate_sku` / `duplicate_barcode` / `insufficient_stock` (409), `rate_limited` (429).",
             "- **Money and quantities** are JSON numbers. The server computes every total, discount, tax, profit and balance — never trust or send client-side totals.",
             "- Timestamps are ISO-8601 UTC (`...Z`); date-only fields are `YYYY-MM-DD`.",
             "- `POST /sales` accepts an optional `client_ref` (idempotency key) so a retried request cannot create two invoices.", ""]
    by_tag: dict[str, list[tuple[str, str, dict]]] = {}
    for path, item in sorted(spec["paths"].items()):
        for method, op in item.items():
            tag = (op.get("tags") or ["other"])[0]
            by_tag.setdefault(tag, []).append((method.upper(), path, op))
    order = {"POST": 0, "GET": 1, "PUT": 2, "PATCH": 3, "DELETE": 4}
    for tag in sorted(by_tag):
        lines += [f"## {tag}", "", "| Method | Path | Summary |", "|---|---|---|"]
        for method, path, op in sorted(by_tag[tag], key=lambda x: (x[1], order.get(x[0], 9))):
            summary = (op.get("summary") or op.get("operationId") or "").replace("_", " ").capitalize()
            lines.append(f"| `{method}` | `{path}` | {summary} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    DOCS.mkdir(exist_ok=True)
    (DOCS / "PERMISSIONS.md").write_text(permissions(), encoding="utf-8")
    (DOCS / "DATABASE.md").write_text(database(), encoding="utf-8")
    (DOCS / "API.md").write_text(api(), encoding="utf-8")
    print("docs regenerated in", DOCS)


if __name__ == "__main__":
    main()
